stages:
  - build
  - deploy

build:
  image: node:14.18.2-alpine
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  script:
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - build/
